language: generic
dist: trusty

env:
  global:
    - secure: "AvAmooFLr6q2f2KWpKuKWq57iJtvETQJMWZV7Olxzh/+Ia9/JJ6E5KtIzQEmSFnFfuMA6Kd1iLE+ioQRSwKo6maSspWG+PJeeD1QHUxfxXjpBosOPC1LHQNns3WisETabhLRh/bw2OhaeSP5USmv9aYRs5Kir/0AJqisICb536+UB1SGqaU2LeE7xOZml+ZAmVV6SAxTIBbcxob09BhchuoNEEXaZsvYOvtNBxvl3PAf3VrkJNYmFeekqteAm4tkuX5iBgm8qiayACyWe8UqCWYvBkxIbcQnrgNaG+j3GF5ObxqfrJ9QBAg34DicFaNY8N46FR0gRLEDOqh40aoLTo+W3V7iK6VtDiy1RTGJWnI5vV5dQr0nBL6frXR0AGhqNpLr6Fp+yk1CJliNs2GgEfS03cCs74+7IoL20lrmcZS4xkGMM1hNdtTDm9SzNJ2+npD+rsLu0cyUD/aG8vZMcIsvOh/X3uUtDeO/8aEayhJcs0FZI0v3gGUjT1kpw/LLmIIYQR3DvwSxfpAmNDIJ7E716wThq860TwAxYur1ThaYp1TgJhirWUjTbROnMwumssydynf8ObANtEPL2HjloWJ++8wznWAqj4YQzZTGrFWVjqwISc7cilr9NlCscThaXY9cyrZm7uq3j3kxbg03mKsD2g/GAdGi8iGcCDrWbsM="
  matrix:
    - DOCKER_TAG=latest

install:
  - openssl aes-256-cbc -K $encrypted_9f0f9f3d5eaa_key -iv $encrypted_9f0f9f3d5eaa_iv -in .travis_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name conao3
  - git config --global user.email conao3@gmail.com

  - git remote -v
  - git remote set-url origin git@github.com:conao3/docker-mustache.git
  - docker login -u=conao3 -p=${DOCKER_PASSWORD}

branches:
  only:
    - master

script:
  - make ci-checkout
  - make && make push TAG=${DOCKER_TAG}

after_success:
  - make ci-merge && make ci-push
